import type { NextApiRequest, NextApiResponse } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "src/lib/auth/next-auth-options";
import { getIdentityCredentials } from "src/lib/clients/iota";
import { ResponseError } from "src/types/types";
import { z } from "zod";
import { v4 as uuidv4 } from "uuid";
import { AwsExchangeCredentialsOK } from "@affinidi-tdk/iota-client";

const iotaStartSchema = z.object({
  iotaConfigurationId: z.string(),
});

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<AwsExchangeCredentialsOK | ResponseError>,
) {
  try {
    const session = await getServerSession(req, res, authOptions);
    if (!session) {
      res.status(401).json({ message: "You must be logged in." });
      return;
    }
    const { iotaConfigurationId } = iotaStartSchema.parse(req.query);

    const identityCredentials = await getIdentityCredentials(
      uuidv4(), // sessionId autogenerated
      iotaConfigurationId,
      session.userId,
    );

    res.status(200).json(identityCredentials);
  } catch (error: any) {
    res.status(500).json({ message: "Unable to get Iota credentials" });
    console.log(error);
  }
}
