name: flutter_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  dio: ^5.4.2+1
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.3.1
  styled_text: ^8.1.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  url_launcher: ^6.2.5
  intl: ^0.19.0
  go_router: ^13.2.2
  google_fonts: ^6.2.1
  get_it: ^7.7.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  retrofit_generator: ^8.1.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-Regular.ttf
        - asset: assets/fonts/DM_Sans/DMSans-Italic.ttf
          style: italic
    - family: DM Sans Bold
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-Bold.ttf
    - family: DM Sans Medium
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-Medium.ttf

  assets:
    - .env
    - assets/
    # - assets/google_logo.svg
    # - assets/apple_logo.png
    # - assets/profile_pic.jpeg
    # - assets/svgs/
    # - assets/animations/ok.json
    # - assets/sunbird-stamp.png
    # - assets/sunbird-logo.svg
    # - assets/android_icon.png
    # - assets/ios_icon.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/android_icon.png"
  image_path_ios: "assets/ios_icon.png"
  adaptive_icon_foreground: "assets/android_icon.png"
  adaptive_icon_background: "#ffffff"  
  min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"
