spring:
  security:
    oauth2:
      client:
        registration:
          javademo:
            client-name: Affinidi Login
            client-id: ${PROVIDER_CLIENT_ID}
            client-secret: ${PROVIDER_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/javademo
            scope: openid,offline_access
            client-authentication-method: client_secret_post
            provider: afflogin
        provider:
          afflogin:
            issuer-uri: ${PROVIDER_ISSUER}
  config:
    import:
      optional:file:.env[.properties]          
logging:
  level:
     org.springframework: WARN
     login.affinidi: INFO
server:
    port: 8080